
exports.seed = function(knex, Promise) {
  return Promise.join(
    // Deletes ALL existing entries
    knex('snp_info').del(),

    // Inserts seed entries
    knex('snp_info').insert([
      {name: 'rs7089424', description: 'If you have GT or GG allele: 1.7x increased risk for acute lymphoblastic leukemia', link: 'http://www.ncbi.nlm.nih.gov/pubmed/20919861?dopt=Abstract', advice_one: 'Monitor yourself for symptoms like pain in your bones, fatigue, fever, loss of appetite, night sweats, bleeding gums, and easy bruising.', advice_two: 'Avoid radiation: may reduce your increased risk below 1.7x.'},
      {name: 'rs53576', description: 'If you have AA or AG allele: Lack of empathy? You have a SNP in the oxytocin receptor which may make you less empathetic than most people. When under stress you may have more difficulty recognizing the emotional state of others.', link: 'http://www.ncbi.nlm.nih.gov/pubmed/19934046?dopt=Abstract', advice_one: 'Engage in a session of Metta meditation. Metta meditation asks you to focus compassion and kindness towards people you love and people you dislike.', advice_two: 'Volunteer somewhere that you might intereact with people who are different than you.'},
      {name: 'rs1800497', description: 'If you have CT or TT allele: More likely to have addictive behavior.', link: 'http://www.ncbi.nlm.nih.gov/pubmed/24528631?dopt=Abstract', advice_one: 'Go to a session with a cognitive behaviorial therapist, who will help you learn to think through your addictive behavior.', advice_two: 'Pick a positive activity you can be \'addicted\' to, like a sport or and art.'},
      {name: 'rs17077540', description: 'If you have AG or GG allele: 1.6x major depressive disorder risk.', link: 'http://www.ncbi.nlm.nih.gov/pubmed/20125088?dopt=Abstract', advice_one: 'If you feel melancholy or unhappy, seek out a monthly therapy session', advice_two: 'Exercise 30 minutes, 3x a week.'},
      {name: 'rs1121980', description: 'If you have CT or TT allele: 1.67x risk for obesity', link: 'http://www.ncbi.nlm.nih.gov/pubmed/18379722?dopt=Abstract', advice_one: 'Set up a meeting with a nutritionist - tell him/her that your genetic risk of obesity is higher so you can make a realistic nutrition plan.', advice_two: 'Get on a solid sleep schedule - go to bed within an hour of the same time each night.'},
      {name: 'rs2241880', description: 'If you do not have CT or CC allele: .26x higher risk for chron\'s disease', link: 'http://www.ncbi.nlm.nih.gov/pubmed/17068223?dopt=Abstract', advice_one: 'If you experience recurring gastrointestinal issues, see a specialist', advice_two: 'Avoid alcohol, diary, and caffiene.'},
      {name: 'rs13266634', description: 'If you have CT or CC allele: increased risk for type-2 diabetes', link: 'http://www.ncbi.nlm.nih.gov/pubmed/17293876?dopt=Abstract', advice_one: 'Commute to work by bike.', advice_two: 'Stay away from sugary drinks: soda, ice tea, and juice.'},
      {name: 'rs2180439', description: 'If you have CT or TT allele: Increased risk of Male Pattern Baldness', link: 'http://www.ncbi.nlm.nih.gov/pubmed/18849994?dopt=Abstract', advice_one: 'If you do not like how your hair looks, experiment with different hair styles.', advice_two: 'Baldness can be related to other conditions, like hyperthyroidism, so check in with your doctor if you experience rapid hair loss.'},
      {name: 'rs307377', description: 'If you have CT or TT allele: Extra tasting ability? Rare T allele, better at detecting umami', link: 'http://www.ncbi.nlm.nih.gov/pubmed/16782140?dopt=Abstract', advice_one: 'Experiment with new foods like cured meats and mushrooms.', advice_two: 'For fun: do a palate test! See if your extra abilities allow you to notice things that others don\'t.'},
      {name: 'rs807701', description: 'If you have CT or CC allele: 2-5x increased dyslexia risk ', link: 'http://www.ncbi.nlm.nih.gov/pubmed/23229871?dopt=Abstract', advice_one: 'If you\'re not sure if you are dyslexic, take a test.', advice_two: 'If you are dyslexic, take the time to find some of the dyslexia learning apps, like SightWords.'},
      {name: 'rs664143', description: 'If you have CT or TT allele: Higher risk for number of cancers', link: 'http://www.ncbi.nlm.nih.gov/pubmed/22203481?dopt=Abstract', advice_one: 'Make friends with your doctor - get tested often.', advice_two: 'Find out it cancer runs in your family and meet with a genetic counselor.'},
      {name: 'rs2802292', description: 'If you have TT allele: Less likely to live to 100. Unfortunately, this version of FOXO3 has reduced longevity.', link: 'http://www.ncbi.nlm.nih.gov/pubmed/19196970?dopt=Abstract', advice_one: 'If you want to increase longevity, the best thing you can do is exercise, at least 30 minutes, 3x a week.', advice_two: 'Stay social, keep making new friends as you age.'},
      {name: 'rs1800955', description: 'If you have CT allele: Increased susceptibility to novelty seeking', link: 'http://www.ncbi.nlm.nih.gov/pubmed/22530780?dopt=Abstract', advice_one: 'Take advantage of this trait when it\'s low risk! Novelty seeking personalities can fit well in jobs that require thinking outside the box or creativity in general.', advice_two: 'Learn techniques for controlling anger, like meditation or writing. Novelty seeking personalities are more likely to lack control over their anger.'},
      {name: 'rs4307059', description: 'If you have CT or TT allele: 1.42x risk of Autism', link: 'http://www.ncbi.nlm.nih.gov/pubmed/19404256?dopt=Abstract', advice_one: 'Self assess for common symptoms like inappropriate social interaction, poor eye contact, compulsive behavior, impulsivity, repetitive movements, self-harm, persistent repetition of words or actions, and learning disabilities.', advice_two: 'If you find out you are on the autism spectrum, seek out a support group of others who are dealing with the same issues.'},
      {name: 'rs10830963', description: 'If you have CG or GG allele: increased type-2 diabetes risk', link: 'http://www.ncbi.nlm.nih.gov/pubmed/19241057?dopt=Abstract', advice_one: 'Eat out less.', advice_two: 'Fill at least half your plate with food that comes from the ground - vegetables, fruits, nuts, and seeds.'}
    ])
  );
};
